Buggity/Models/CodeFirst/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Buggity.Models.CodeFirst
{
    public class Project
    {
        public Project()
        {
            this.Tickets = new HashSet<Ticket>();
            
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public Guid Id { get; set; }
        [Display(Name = "Created Date")]
        public DateTimeOffset Created { get; set; }
        [Display(Name = "Updated Date")]
        public DateTimeOffset? Updated { get; set; }
        [Display(Name ="Project Name")]
        public string Title { get; set; }
        public string Status { get; set; }
        public string Priority { get; set; }
        public string Owner { get; set; }
        [AllowHtml]
        [Display(Name = "Description")]
        public string Body { get; set; }
        public virtual ICollection<Ticket> Tickets { get; set; }
       
        public string UserId { get; set; }
        public virtual ICollection<ApplicationUser> ApplicationUsers { get; set; }


    }
}

Buggity/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Buggity.Models;
using Microsoft.AspNet.Identity;
using Buggity.Models.CodeFirst;
using System.Xml.Linq;
using PagedList;
using Buggity.Helpers;

namespace Buggity.Controllers
{
    [Authorize]
    public class ProjectsController : Controller
    {
        private ApplicationDbContext db;
        private Helpers.UserRolesHelper helper;
        List<Project> projectslist = new List<Project>();

        public ProjectsController()
        {
            db = new ApplicationDbContext();
            helper = new Helpers.UserRolesHelper(db);
        }
        // GET: Projects
        [Authorize(Roles = "Admin, PM, Submitter,Developer")]
        public ActionResult Index(int? page)
        {
           

            string userId = User.Identity.GetUserId();
            bool usrIsAdmiNOrPM = helper.IsUserInAnyRole(userId, "Admin", "PM");


            foreach (var item in db.Project.ToList())
            {
                ApplicationUser usr = db.Users.Find(item.UserId);

                projectslist.Add(new Project
                {
                    Id = item.Id,
                    Title = item.Title,
                    Body = item.Body,
                    //Owner = item.Owner,
                    Created = item.Created,
                    Updated = item.Updated,
                    //Priority =item.Priority,
                    //Status = item.Status,
                    UserId = item.UserId,

                });

            }



            if (usrIsAdmiNOrPM) // if logged in user is admin 
            {


                return View(projectslist.OrderBy(x => x.Id).ToList());
                //all projects
            }
            else
            {
               // ApplicationUser usr = db.Users.Find(userId);
               

                    //var dbproject = db.Project.Include(p => p.ApplicationUsers);
                    //var list = projectslist.Where(x => x.UserId == usr.Id)

                    //    .OrderBy(x => x.Id).ToList();
                    var usr = db.Users.Find(User.Identity.GetUserId());

                    var rolesHelper = new UserRolesHelper(db);
                    if (rolesHelper.IsUserInRole(usr.Id, "Developer"))
                    {


                        //projectslist.Clear();


                    var dbproject = db.Project.Include(p => p.ApplicationUsers).Where(x => x.UserId == usr.Id).ToList();

                    foreach (var item in dbproject)
                    {
                        projectslist.Add(new Project
                        {
                            Id = item.Id,
                            Title = item.Title,
                            Body = item.Body,
                            //Owner = item.Owner,
                            Created = item.Created,
                            Updated = item.Updated,
                            //Priority =item.Priority,
                            //Status = item.Status,
                            UserId = item.UserId
                        });
                    }

                    //string userselected = null;
                    //projectslist.Clear();

                    //foreach (var item in dbproject)
                    //{
                    //    var sss = item.ApplicationUsers.Where(x => x.Id == usr.Id);

                    //    foreach (var itemuser in sss)
                    //    {
                    //        userselected = itemuser.Id;
                    //    }

                    //    if (userselected != null)
                    //    {
                    //        projectslist.Add(new Project
                    //        {
                    //            Id = item.Id,
                    //            Title = item.Title,
                    //            Body = item.Body,
                    //            //Owner = item.Owner,
                    //            Created = item.Created,
                    //            Updated = item.Updated,
                    //            //Priority =item.Priority,
                    //            //Status = item.Status,
                    //            UserId = userselected


                    //        });

                    //    }
                    //}
                    return View(projectslist);//user's projects.
                }
                else
                    return View();
            }

        }


        // GET: Projects/Details/5
        [Authorize(Roles = "Admin, PM, Developer")]
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Project.Find(id);



            project.ApplicationUsers.Where(x => x.Id == id.ToString());

            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // GET: Projects/Create

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            // get all users 

            var userlisted = GetApplicationUsersInRole("PM");

            var list = userlisted.OrderBy(r => r.Email).ToList().Select(rr => new SelectListItem { Value = rr.Id.ToString(), Text = rr.Email }).ToList();
            ViewBag.PMUsers = list;
            return View();
        }

        // show all users with specific role
        public IEnumerable<ApplicationUser> GetApplicationUsersInRole(string roleName)
        {
            return from role in db.Roles
                   where role.Name == roleName
                   from userRoles in role.Users
                   join user in db.Users
                   on userRoles.UserId equals user.Id
                   select user;
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        //public ActionResult Create([Bind(Include = "Id,Created,Updated,Title,Status,Priority,Owner,Body,UserId")] Project project)
        public ActionResult Create([Bind(Include = "Id,Title,Status,Priority,Owner,Body,UserId")] Project project)
        {
            if (ModelState.IsValid)
            {
                project.Id = Guid.NewGuid();

                project.Created = DateTimeOffset.Now;
                project.Updated = DateTimeOffset.Now;
                db.Project.Add(project);


                db.SaveChanges();

                return RedirectToAction("Index");
            }

            var userlisted = GetApplicationUsersInRole("PM");

            var list = userlisted.OrderBy(r => r.Email).ToList().Select(rr => new SelectListItem { Value = rr.Id.ToString(), Text = rr.Email }).ToList();
            ViewBag.PMUsers = list;


            return View(project);
        }

        [Authorize(Roles = "Admin")]
        // GET: Projects/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Project.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "Id,Created,Updated,Title,Status,Priority,Owner,Body,UserId")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(project);
        }

        // GET: Projects/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Project.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Project project = db.Project.Find(id);
            db.Project.Remove(project);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult _userProjects(Project proj)
        {
            // TODO 
            List<SelectListItem> li = new List<SelectListItem>();


            foreach (var appusr in proj.ApplicationUsers)
            {
                li.Add(new SelectListItem { Text = appusr.FirstName + appusr.LastName, Value = appusr.Id });
            }

            ViewData["ProjAppUsers"] = li;
            return PartialView(proj);
        }

        [Authorize(Roles = "Admin, PM")]
        public ActionResult AddProjectUsers(Project project)
        {

            Project proj = db.Project.Find(project.Id);

Buggity/Controllers/RolesController.cs
using Buggity.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;


namespace Buggity.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class RolesController : Controller
    {  
        ApplicationDbContext context;       
        private Helpers.UserRolesHelper urhelper;

        public RolesController()
        {
            context = new ApplicationDbContext();
            urhelper = new Helpers.UserRolesHelper(context);
        }

        // GET: Roles
        //[Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var Roles = context.Roles.ToList();
            return View(Roles);
        }



        // Create  a New role
        //[Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            var Role = new IdentityRole();
            return View(Role);
        }
        //[Authorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult Create(IdentityRole Role)
        {

            context.Roles.Add(Role);
            context.SaveChanges();

            return RedirectToAction("Index");
        }


        //[Authorize(Roles = "Admin")]
        public ActionResult ManageUserRoles()
        {
            //roles for the view dropdown
            var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr =>

            new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            ViewBag.Roles = list;
            return View();
        }


    

    [HttpPost]
        //[Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
    public async Task<ActionResult> RoleAddToUser(string UserName, string RoleName)
    {
        ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

        // var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(context));
        var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));

        if (user.Id != "")
        {
            await UserManager.AddToRoleAsync(user.Id, RoleName);

            ViewBag.ResultMessage = "Role created successfully !";
        }

        else
        {
            ViewBag.ResultMessage = "Error While creating Role  !";
        }

        // roles for the view dropdown
        var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
        ViewBag.Roles = list;

        return View("ManageUserRoles");
    }


    [HttpPost]
        //[Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
    public ActionResult GetRoles(string UserName)
    {
        if (!string.IsNullOrWhiteSpace(UserName))
        {
            ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

                List<SelectListItem> list = new List<SelectListItem>();
            if (user!=null)
            { 
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));


                ViewBag.RolesForThisUser = UserManager.GetRoles(user.Id);

                // roles for the view dropdown
                list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
            }
                ViewBag.Roles = list;
        }

        return View("ManageUserRoles");
    }



    [HttpPost]
        //[Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
    public ActionResult DeleteRoleForUser(string UserName, string RoleName)
    {
        var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));

        ApplicationUser user = context.Users.Where(u => u.UserName.Equals(UserName, StringComparison.CurrentCultureIgnoreCase)).FirstOrDefault();

        if (urhelper.IsUserInRole(user.Id, RoleName))
        {
            UserManager.RemoveFromRole(user.Id, RoleName);
            ViewBag.ResultMessage = "Role removed from this user successfully!";
        }
        else
        {
            ViewBag.ResultMessage = "This user doesn't belong to selected role!";
        }
        // roles for the view dropdown
        var list = context.Roles.OrderBy(r => r.Name).ToList().Select(rr => new SelectListItem { Value = rr.Name.ToString(), Text = rr.Name }).ToList();
        ViewBag.Roles = list;

        return View("ManageUserRoles");
    }
  }
}

Buggity/Views/Projects/AddProjectUsers.cshtml
@model List<SelectListItem>

@{
    ViewBag.Title = "Assign a user to project";
}

<h2>Edit</h2>

@using (Html.BeginForm("AddUserToProject","Projects",FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Project</h4>
        @Html.Hidden("projectId",ViewData["projectId"].ToString())
        <hr />
        <div class="form-group">
            
            <div class="col-md-10">
                @Html.DropDownList("AvailableUserId", Model, "Available users:",
               new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Buggity/Views/Projects/AdminDashboard.cshtml
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "AdminDashboard";
}

<h2>Admin Dashboard</h2>

<div class="dt-head-left">

    @Html.ActionLink("Welcome " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })


</div>

<br />
<br />

<div class="header">



    @Html.ActionLink("View Projects", "Index", null, new { @class = "btn-primary btn-lg" })<br /><br />


</div>

<br />

<div class="header">



    @Html.ActionLink("Create Project","Create", "Projects", null, new { @class = "btn-primary btn-lg" })<br /><br />


</div>

<br />

<div class="header">



    @Html.ActionLink("View Tickets", "Index", "Tickets", null, new { @class = "btn-primary btn-lg" })<br /><br />


</div>

Buggity/Views/Projects/Create.cshtml
@model Buggity.Models.CodeFirst.Project

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @*@Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })*@
                @*@Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.Updated, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Updated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Updated, "", new { @class = "text-danger" })*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.Owner, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Owner, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Owner, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Body, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.DropDownListFor(model => model.UserId, (IEnumerable<SelectListItem>)ViewBag.PMUsers, new { htmlAttributes = new { @class = "form-control" } })

                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Buggity/Views/Projects/Delete.cshtml
@model Buggity.Models.CodeFirst.Project

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Updated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Owner)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Owner)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Buggity/Views/Projects/Details.cshtml
@model Buggity.Models.CodeFirst.Project
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "Details";
    string userId = Request.IsAuthenticated ? User.Identity.GetUserId() : "";
}





    

<h2>Details</h2>

<div>
    <h4>Project</h4>
    <hr />
    
  
    
    <dl id="Table" class="dl-horizontal" style="outline-color:aqua">

       
        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Updated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Updated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Owner)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Owner)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationUsers.Where(x => x.Id == model.Id)
        </dd>*@

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-danger" })
    @*@Html.ActionLink("Back to List", "Index") |
    @Html.ActionLink("Manage Users", "projectUsers")*@
</p>





<div class="container body-content">

    @*@RenderBody()
        <hr />*@
    @{ Html.RenderAction("_userProjects", Model);}

</div>

<br />
<br />

<div class="container body-content">

    @*@RenderBody()
        <hr />*@
    @{ Html.RenderAction("_projectTickets", new { ProjectId = Model.Id, UserId = userId });}

</div>

  

Buggity/Views/Projects/DeveloperDashboard.cshtml
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "DeveloperDashboard";
}

<h2>Developer Dashboard</h2>

<div class="dt-head-left">

    @Html.ActionLink("Welcome " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })


</div>

<br />
<br />

<div class="header">



    @Html.ActionLink("View Projects", "Index", null, new { @class = "btn-primary btn-lg" })<br /><br />


</div>

<br />

<div class="header">



    @Html.ActionLink("View Tickets", "Index", "Tickets", null, new { @class = "btn-primary btn-lg" })<br /><br />


</div>

Buggity/Views/Projects/PmDashboard.cshtml
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "PmDashboard";
}

<h2>PM Dashboard</h2>

<div class="dt-head-left">

    @Html.ActionLink("Welcome " + User.Identity.GetUserName() + "!", "Index", "Manage", routeValues: null, htmlAttributes: new { title = "Manage" })


</div>

<br />
<br />

<div class="header">



    @Html.ActionLink("View Projects", "Index", null, new { @class = "btn-primary btn-lg" })<br /><br />


</div>

<br />

<div class="header">



    @Html.ActionLink("View Tickets", "Index", "Tickets", null, new { @class = "btn-primary btn-lg" })<br /><br />


</div>

Buggity/Views/Projects/_userProjects.cshtml
@*@Model Buggity.Models.CodeFirst.Project*@
    @{
        ViewBag.Title = "Manage Project Users";
        //Layout = "~/Views/Projects/Details.cshtml";

        var lstUsrProj = ViewData.ContainsKey("ProjAppUsers") 
            ? ((List<SelectListItem>)ViewData["ProjAppUsers"]) : (new List<SelectListItem>());
    }


    <h2>@ViewBag.Title</h2>
@using (Html.BeginForm("RemoveUserFromProject", "Projects", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("projectId", ((Buggity.Models.CodeFirst.Project)Model).Id.ToString())
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-10">
                @Html.DropDownList("AvailableUserId", lstUsrProj,"Available users:",
               new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Remove" class="btn btn-default" />
            </div>
        </div>
    </div>

}
            <br />
            <br />
            @Html.ActionLink("Back to List", "Index") |
          @if (User.Identity.IsAuthenticated)
          {
              if (User.IsInRole("Admin, PM"))
              {
                @Html.ActionLink("Add a user", "AddProjectUsers", (Buggity.Models.CodeFirst.Project)Model)
              }
          }  


@Html.ActionLink("Add a user", "AddProjectUsers", (Buggity.Models.CodeFirst.Project)Model)


            @ViewBag.ResultMessage

Buggity/Views/Projects/projectUsers.cshtml
@{
    ViewBag.Title = "projectUsers";
}

<h2>Edit Users For Project</ h2 >


@using(Html.BeginForm("RoleAddToUser", "Roles"))
{
    @*@Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <p>
            Username : @Html.TextBox("UserName")
            Role Name: @Html.DropDownList("RoleName", (IEnumerable<SelectListItem>)ViewBag.Roles, "Select...")

        </p>*@

    <input type="submit" value="Save" />




}
<hr />


<hr />
@*<h3>Delete user from project</h3>

@using (Html.BeginForm("DeleteRoleForUser", "Roles"))
{
    @*@*@*@Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <p>
            Username : @Html.TextBox("UserName")
            Role Name: @Html.DropDownList("RoleName", (IEnumerable<SelectListItem>)ViewBag.Roles, "Select ...")

        </p>*@

    @*<input type="submit" value="Delete this user from Role" />*@
@*@